
package com.athieme;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "MockWebService", targetNamespace = "http://athieme.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface MockWebService {


    /**
     * 
     * @param value
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String reverse(
        @WebParam(name = "value", partName = "value")
        String value);

    /**
     * 
     * @param value
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    public String echo(
        @WebParam(name = "value", partName = "value")
        String value);

}
