
package com.athieme;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "MockWebServiceService", targetNamespace = "http://athieme.com/", wsdlLocation = "http://localhost:9999/webservice/mock?wsdl")
public class MockWebServiceService
    extends Service
{

    private final static URL MOCKWEBSERVICESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.athieme.MockWebServiceService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.athieme.MockWebServiceService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:9999/webservice/mock?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:9999/webservice/mock?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        MOCKWEBSERVICESERVICE_WSDL_LOCATION = url;
    }

    public MockWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MockWebServiceService() {
        super(MOCKWEBSERVICESERVICE_WSDL_LOCATION, new QName("http://athieme.com/", "MockWebServiceService"));
    }

    /**
     * 
     * @return
     *     returns MockWebService
     */
    @WebEndpoint(name = "MockWebServicePort")
    public MockWebService getMockWebServicePort() {
        return super.getPort(new QName("http://athieme.com/", "MockWebServicePort"), MockWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MockWebService
     */
    @WebEndpoint(name = "MockWebServicePort")
    public MockWebService getMockWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://athieme.com/", "MockWebServicePort"), MockWebService.class, features);
    }

}
